#!/bin/bash

echo "🚀 AI创业诊断工具部署助手"
echo "=========================="
echo ""
echo "请选择部署方式："
echo "1. GitHub Pages（推荐，完全免费）"
echo "2. Vercel（需要账号，功能更强大）"
echo "3. Netlify（类似Vercel的替代）"
echo ""
read -p "请输入选择 (1/2/3): " choice

case $choice in
    1)
        echo ""
        echo "📦 GitHub Pages部署步骤："
        echo "========================"
        echo ""
        echo "第一步：创建GitHub仓库"
        echo "1. 访问 https://github.com/new"
        echo "2. 仓库名: ai-startup-diagnosis"
        echo "3. 选择 Public"
        echo "4. 不要初始化README"
        echo "5. 点击 Create repository"
        echo ""
        echo "第二步：上传文件"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "cd /home/brandonclaw/.openclaw/workspace/deploy"
        echo "git init"
        echo "git add ."
        echo "git commit -m 'Initial commit: AI创业诊断工具'"
        echo "git branch -M main"
        echo "git remote add origin https://github.com/你的用户名/ai-startup-diagnosis.git"
        echo "git push -u origin main"
        echo "----------------------------------------"
        echo ""
        echo "第三步：开启GitHub Pages"
        echo "1. 进入仓库设置: Settings > Pages"
        echo "2. Source: 选择 'Deploy from a branch'"
        echo "3. Branch: 选择 'main' 和 '/ (root)'"
        echo "4. 点击 Save"
        echo "5. 等待几分钟，访问提供的链接"
        echo ""
        echo "你的网站将在: https://你的用户名.github.io/ai-startup-diagnosis"
        ;;
    
    2)
        echo ""
        echo "☁️ Vercel部署步骤："
        echo "=================="
        echo ""
        echo "第一步：安装Vercel CLI"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "npm install -g vercel"
        echo "----------------------------------------"
        echo ""
        echo "第二步：登录Vercel"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "cd /home/brandonclaw/.openclaw/workspace/deploy"
        echo "vercel login"
        echo "# 按照提示在浏览器中完成登录"
        echo "----------------------------------------"
        echo ""
        echo "第三步：部署项目"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "cd /home/brandonclaw/.openclaw/workspace/deploy"
        echo "vercel --prod"
        echo "# 回答部署问题（全部按回车用默认值）"
        echo "----------------------------------------"
        echo ""
        echo "部署完成后会显示你的网站链接"
        ;;
    
    3)
        echo ""
        echo "🌐 Netlify部署步骤："
        echo "==================="
        echo ""
        echo "第一步：安装Netlify CLI"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "npm install -g netlify-cli"
        echo "----------------------------------------"
        echo ""
        echo "第二步：登录Netlify"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "cd /home/brandonclaw/.openclaw/workspace/deploy"
        echo "netlify login"
        echo "# 按照提示在浏览器中完成登录"
        echo "----------------------------------------"
        echo ""
        echo "第三步：部署项目"
        echo "复制以下命令执行："
        echo "----------------------------------------"
        echo "cd /home/brandonclaw/.openclaw/workspace/deploy"
        echo "netlify deploy --prod"
        echo "# 按照提示操作"
        echo "----------------------------------------"
        ;;
    
    *)
        echo "无效选择"
        ;;
esac

echo ""
echo "🎯 部署完成后："
echo "1. 测试网站功能"
echo "2. 分享链接给我测试"
echo "3. 开始推广获取用户"
echo ""
echo "需要帮助随时问我！🦐"